# Generated by Django 4.0 on 2022-01-15 21:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0008_alter_hole_options'),
        ('league', '0011_league_club'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('name', models.CharField(help_text='Event Name ex: week 5', max_length=150)),
                ('format', models.CharField(choices=[('two-man-combined', 'Two Man Combined'), ('two-man-mp-scramble', 'Two Man Matchplay Scramble'), ('four-ball', 'Four-Ball'), ('foursomes', 'Foursomes')], max_length=50)),
                ('date', models.DateTimeField()),
                ('side_played', models.CharField(choices=[('front', 'Front'), ('back', 'Back'), ('both', 'Both')], max_length=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='league.league')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('teams', models.ManyToManyField(to='league.Team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamScorecard',
            fields=[
                ('scores', models.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.team')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='PlayerScorecard',
            fields=[
                ('handicap', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('scores', models.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.player')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
