# Generated by Django 4.0 on 2022-04-26 18:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('name', models.CharField(help_text='Event Name ex: week 5', max_length=150)),
                ('format', models.CharField(choices=[('two-man-comb-matchplay', 'Two Man Combined Matchplay'), ('two-man-mp-scramble', 'Two Man Matchplay Scramble'), ('four-ball', 'Four-Ball'), ('foursomes', 'Foursomes')], max_length=50)),
                ('date', models.DateField()),
                ('side_played', models.CharField(choices=[('Front', 'Front'), ('Back', 'Back'), ('Both', 'Both')], max_length=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('name', models.CharField(blank=True, help_text='leave blank', max_length=50, null=True)),
                ('cards_made', models.BooleanField(default=False)),
                ('current_hole', models.PositiveSmallIntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name_plural': 'matches',
                'ordering': ['event__league', 'event__date'],
            },
        ),
        migrations.CreateModel(
            name='MatchHandicap',
            fields=[
                ('hdcp', models.JSONField(blank=True, default=dict, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['match__event__league', 'created'],
            },
        ),
        migrations.CreateModel(
            name='PlayerScorecard',
            fields=[
                ('handicap', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('scores', models.JSONField(blank=True, default=dict)),
                ('front', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('back', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('total', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='TeamScorecard',
            fields=[
                ('handicap', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('scores', models.JSONField(blank=True, default=dict, null=True)),
                ('front', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('back', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('points', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.match')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
