# Generated by Django 4.0 on 2022-01-15 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='format',
            field=models.CharField(choices=[('two-man-comb-matchplay', 'Two Man Combined Matchplay'), ('two-man-mp-scramble', 'Two Man Matchplay Scramble'), ('four-ball', 'Four-Ball'), ('foursomes', 'Foursomes')], max_length=50),
        ),
    ]
