# Generated by Django 4.0 on 2022-04-26 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('league', '0001_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamscorecard',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.team'),
        ),
        migrations.AddField(
            model_name='playerscorecard',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.match'),
        ),
        migrations.AddField(
            model_name='playerscorecard',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.player'),
        ),
        migrations.AddField(
            model_name='playerscorecard',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='league.team'),
        ),
        migrations.AddField(
            model_name='matchhandicap',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.match'),
        ),
        migrations.AddField(
            model_name='matchhandicap',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
        migrations.AddField(
            model_name='match',
            name='opponent_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home', to='league.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='opponent_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away', to='league.team'),
        ),
        migrations.AddField(
            model_name='event',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
        migrations.AddField(
            model_name='event',
            name='league',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='league.league'),
        ),
    ]
