# Generated by Django 4.0 on 2022-04-27 17:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, help_text='leave blank', null=True, size=None),
        ),
        migrations.AddField(
            model_name='match',
            name='team2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, help_text='leave blank', null=True, size=None),
        ),
    ]
