# Generated by Django 4.0 on 2022-01-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_match_options_match_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_hdcp',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
