# Generated by Django 4.0 on 2022-04-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_match_team1_match_team2'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerscorecard',
            name='name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='teamscorecard',
            name='name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='playerscorecard',
            name='scores',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
