# Generated by Django 4.0 on 2022-01-21 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0012_alter_team_options'),
        ('events', '0004_match_match_hdcp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='match_hdcp',
        ),
        migrations.AlterField(
            model_name='match',
            name='teams',
            field=models.ManyToManyField(blank=True, to='league.Team'),
        ),
    ]
