# Generated by Django 4.0 on 2022-02-01 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_match_match_hdcp_alter_match_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamscorecard',
            name='handicap',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
