# Generated by Django 4.0 on 2022-02-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_playerscorecard_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='hdcp',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
