# Generated by Django 4.0 on 2022-02-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0012_alter_team_options'),
        ('events', '0008_match_hdcp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='hdcp',
            field=models.JSONField(blank=True, help_text='leave blank', null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='teams',
            field=models.ManyToManyField(help_text='Select Two Teams', to='league.Team'),
        ),
    ]
