# Generated by Django 4.0 on 2022-02-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0012_alter_team_options'),
        ('events', '0009_alter_match_hdcp_alter_match_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='teams',
            field=models.ManyToManyField(help_text='Select Two Teams \n', to='league.Team'),
        ),
    ]
