# Generated by Django 4.0 on 2022-02-07 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0012_alter_team_options'),
        ('events', '0010_alter_match_teams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='teams',
        ),
        migrations.AddField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='league.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='league.team'),
        ),
    ]
