# Generated by Django 4.0 on 2022-02-07 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_remove_match_teams_match_team1_match_team2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='team1',
            new_name='opponent_1',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='team2',
            new_name='opponent_2',
        ),
    ]
