# Generated by Django 4.0 on 2022-02-09 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_rename_team1_match_opponent_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamscorecard',
            name='points',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teamscorecard',
            name='scores',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
