# Generated by Django 4.0 on 2022-02-12 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_teamscorecard_points_alter_teamscorecard_scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerscorecard',
            name='scores',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
