# Generated by Django 4.0 on 2022-02-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_alter_playerscorecard_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='cards_made',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='current_hole',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
