# Generated by Django 4.0 on 2022-02-16 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_match_cards_made_match_current_hole'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerscorecard',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='teamscorecard',
            options={'ordering': ['created']},
        ),
    ]
