# Generated by Django 4.0 on 2022-03-05 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_alter_event_side_played'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamscorecard',
            name='points',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
