# Generated by Django 4.0 on 2022-03-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_alter_teamscorecard_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerscorecard',
            name='total',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
