# Generated by Django 4.0 on 2022-03-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_playerscorecard_back_playerscorecard_front_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerscorecard',
            name='scores',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
