# Generated by Django 4.0 on 2022-03-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_alter_playerscorecard_scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamscorecard',
            name='points',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
