# Generated by Django 4.0 on 2022-03-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_teamscorecard_back_teamscorecard_front_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerscorecard',
            name='total',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
