# Generated by Django 4.0 on 2022-04-21 18:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_remove_match_hdcp_matchhandicap'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchhandicap',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
