# Generated by Django 4.0 on 2022-04-21 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_matchhandicap_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchhandicap',
            options={'ordering': ['created']},
        ),
    ]
