# Generated by Django 4.0 on 2022-04-26 18:19

import course.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('name', models.CharField(help_text='Formal name for the golf course (ex: Augusta National Golf Course)', max_length=150)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('PR', 'Puerto Rico'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=2)),
                ('zip', models.CharField(blank=True, max_length=12, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('has_multiple_courses', models.BooleanField(default=False, help_text='Check here if the club has more than one course.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('name', models.CharField(help_text='If the club has just one course, use a simple version of the club\'s formal name (example: Augusta National Golf Course would be "Augusta")', max_length=25)),
                ('yards_out', models.PositiveSmallIntegerField(help_text='Front nine total yards.')),
                ('par_out', models.PositiveSmallIntegerField(help_text='Front nine par total.')),
                ('yards_in', models.PositiveSmallIntegerField(help_text='Back nine total yards.')),
                ('par_in', models.PositiveSmallIntegerField(help_text='Back nine par total.')),
                ('yards_total', models.PositiveSmallIntegerField(help_text='Front + Back total yards')),
                ('par_total', models.PositiveSmallIntegerField(help_text='Front + Back par')),
                ('is_nine', models.BooleanField(default=False, help_text='Check here if this course is a nine-hole course.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.club')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Hole',
            fields=[
                ('number', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(18), django.core.validators.MinValueValidator(1)])),
                ('par', models.PositiveSmallIntegerField(choices=[(3, '3'), (4, '4'), (5, '5')])),
                ('handicap', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(18), django.core.validators.MinValueValidator(1)])),
                ('yardage', models.PositiveSmallIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=course.models.create_path)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
            options={
                'ordering': ['course', 'number'],
            },
        ),
    ]
