# Generated by Django 4.0 on 2022-01-12 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='club',
        ),
        migrations.RemoveField(
            model_name='hole',
            name='course',
        ),
        migrations.DeleteModel(
            name='Club',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Hole',
        ),
    ]
