# Generated by Django 4.0 on 2022-01-12 19:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hole',
            name='handicap',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(18), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='hole',
            name='number',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(18), django.core.validators.MinValueValidator(1)]),
        ),
    ]
