# Generated by Django 4.0 on 2022-01-12 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_hole_handicap_alter_hole_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name']},
        ),
    ]
