# Generated by Django 4.0 on 2022-01-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_club_options_alter_course_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(help_text='Formal name for the golf course (ex: Augusta National Golf Course)', max_length=150),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(help_text='If the club has just one course, use simple version of the club name (example: Augusta National Golf Course would be "Augusta")', max_length=25),
        ),
    ]
