# Generated by Django 4.0 on 2022-01-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_club_name_alter_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(help_text='If the club has just one course, use a simple version of the club\'s formal name (example: Augusta National Golf Course would be "Augusta")', max_length=25),
        ),
    ]
