# Generated by Django 4.0 on 2022-01-31 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_hole_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='par_in',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='par_out',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='par_total',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='yards_in',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='yards_out',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='yards_total',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
