# Generated by Django 4.0 on 2022-01-31 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_course_par_in_course_par_out_course_par_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='par_in',
            field=models.PositiveSmallIntegerField(help_text='Back nine par total.'),
        ),
        migrations.AlterField(
            model_name='course',
            name='par_out',
            field=models.PositiveSmallIntegerField(help_text='Front nine par total.'),
        ),
        migrations.AlterField(
            model_name='course',
            name='par_total',
            field=models.PositiveSmallIntegerField(help_text='Front + Back par'),
        ),
        migrations.AlterField(
            model_name='course',
            name='yards_in',
            field=models.PositiveSmallIntegerField(help_text='Back nine total yards.'),
        ),
        migrations.AlterField(
            model_name='course',
            name='yards_out',
            field=models.PositiveSmallIntegerField(help_text='Front nine total yards.'),
        ),
        migrations.AlterField(
            model_name='course',
            name='yards_total',
            field=models.PositiveSmallIntegerField(help_text='Front + Back total yards'),
        ),
    ]
