# Generated by Django 4.0 on 2022-01-02 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_player_handicap_player_is_admin_player_is_sub_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='email',
        ),
        migrations.RemoveField(
            model_name='player',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='player',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='username',
        ),
    ]
