# Generated by Django 4.0 on 2022-01-03 03:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_alter_player_first_name_alter_player_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league',
            old_name='league_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='league',
            old_name='league_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='league_id',
            new_name='league',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='team_id',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='player',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='team_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='league_id',
            new_name='league',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='team_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='player',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
