# Generated by Django 4.0 on 2022-01-13 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0008_alter_player_options_alter_player_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
