# Generated by Django 4.0 on 2022-01-13 02:02

from django.db import migrations, models
import league.models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0009_alter_league_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='profile_image',
            field=models.ImageField(blank=True, default='profiles/user-default.png', null=True, upload_to=league.models.create_path),
        ),
    ]
