# Generated by Django 4.0 on 2022-01-13 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_hole_options'),
        ('league', '0010_alter_player_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.club'),
        ),
    ]
