# Generated by Django 4.0 on 2022-01-20 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0011_league_club'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['-name']},
        ),
    ]
