# Generated by Django 4.0 on 2022-03-03 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0013_team_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='record',
            field=models.JSONField(blank=True, default=dict, help_text='leave blank'),
        ),
    ]
