# Generated by Django 4.0 on 2022-03-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0014_alter_team_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='pints',
            field=models.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='team',
            name='record',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
