# Generated by Django 4.0 on 2022-03-05 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0015_team_pints_alter_team_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='pints',
        ),
    ]
